#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════
#   ⚡️ 3OUTHBOY UserBot — Interactive Installer
#   Ubuntu 20.04+ / Debian 11+  |  Run as root
#   Usage:  bash install.sh
# ═══════════════════════════════════════════════════════

R="\e[0m"; B="\e[1m"; G="\e[32m"; C="\e[36m"; Y="\e[33m"; RD="\e[31m"
LINE="═══════════════════════════════════════════════════"

banner() {
  echo -e "${C}${LINE}${R}"
  echo -e "${B}     ⚡️  3OUTHBOY UserBot — Installer  ⚡️${R}"
  echo -e "${C}${LINE}${R}"
}
step() { echo -e "\n${G}▶${R} ${B}$1${R}"; }
info() { echo -e "  ${C}$1${R}"; }
ok()   { echo -e "  ${G}✓ $1${R}"; }
warn() { echo -e "  ${Y}⚠ $1${R}"; }
fail() { echo -e "  ${RD}✖ $1${R}"; exit 1; }

banner

# ── root check ──
if [[ $EUID -ne 0 ]]; then
  fail "Please run as root:  sudo bash install.sh"
fi

DIR="$(cd "$(dirname "$0")" && pwd)"
info "Install folder: ${DIR}"

# ── 1/5 system packages ──
step "1/5  Installing system packages..."
export DEBIAN_FRONTEND=noninteractive
apt update -y
apt install -y python3 python3-pip python3-venv git build-essential

PYV=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
info "Python version: ${PYV}"
if [[ "$(python3 -c 'import sys; print(1 if sys.version_info < (3,9) else 0)')" == "1" ]]; then
  warn "Python older than 3.9 — the bot may not work correctly!"
fi

# ── 2/5 virtual environment & libraries ──
step "2/5  Creating virtual environment & installing libraries..."
if [[ ! -d "${DIR}/venv" ]]; then
  python3 -m venv "${DIR}/venv"
fi
PIP="${DIR}/venv/bin/pip"
"${PIP}" install --upgrade pip -q
if [[ -f "${DIR}/requirements.txt" ]]; then
  "${PIP}" install -r "${DIR}/requirements.txt" || "${PIP}" install pyrogram aiohttp tzdata
else
  "${PIP}" install pyrogram aiohttp tzdata
fi
ok "Libraries installed"

# ── 3/5 configuration ──
step "3/5  Configuration"
SKIPCONF=0
if [[ -f "${DIR}/config.py" ]]; then
  warn "config.py already exists."
  read -p "  Re-configure? (y/N): " RECONF
  if [[ "$RECONF" != "y" ]]; then
    info "Keeping existing config."
    SKIPCONF=1
  fi
fi

if [[ "$SKIPCONF" == "0" ]]; then
  echo
  echo -e "${Y}  ─ Get API_ID & API_HASH:  https://my.telegram.org${R}"
  echo -e "${Y}  ─ Get BOT_TOKEN:  @BotFather${R}"
  echo -e "${Y}  ─ Get your numeric ID:  @userinfobot${R}"
  echo
  info "💡 TIP: Just paste values as-is — the installer"
  info "   handles quotes, spaces & formatting automatically!"

  # ── helper: clean input (strip spaces & quotes) ──
  clean() {
    local val="$1"
    val="${val//[\"\']/}"   # remove all " and '
    val="${val// /}"        # remove spaces
    printf '%s' "${val}"
  }

  # ── API_ID (must be a number) ──
  while :; do
    read -p "  🔑 API_ID (number): " RAW
    API_ID="$(clean "$RAW")"
    [[ "$API_ID" =~ ^[0-9]+$ ]] && break
    warn "API_ID must be a number — try again!"
  done

  # ── API_HASH ──
  while :; do
    read -p "  🔑 API_HASH: " RAW
    API_HASH="$(clean "$RAW")"
    [[ -n "$API_HASH" ]] && break
    warn "API_HASH can't be empty — try again!"
  done

  # ── BOT_TOKEN (optional) ──
  read -p "  🤖 BOT_TOKEN (Enter to skip panel bot): " RAW
  BOT_TOKEN="$(clean "$RAW")"
  if [[ -z "$BOT_TOKEN" ]]; then
    warn "Skipped — you can add it later in config.py"
  elif [[ "$BOT_TOKEN" != *:* ]]; then
    warn "⚠ That doesn't look like a valid token (no ':' found) — saving anyway"
  fi

  # ── OWNER_ID (must be a number) ──
  while :; do
    read -p "  👤 OWNER_ID (your numeric Telegram ID): " RAW
    OWNER_ID="$(clean "$RAW")"
    [[ "$OWNER_ID" =~ ^[0-9]+$ ]] && break
    warn "OWNER_ID must be a number — try again!"
  done

  # ── AI_API_KEY (optional) ──
  read -p "  🧠 AI_API_KEY (Enter to skip): " RAW
  AI_KEY="$(clean "$RAW")"

  # ── write config.py (quotes handled automatically!) ──
  cat > "${DIR}/config.py" <<EOF
# ⚙️ 3OUTHBOY UserBot — generated by installer
# ⚠️ PRIVATE — never share this file!

API_ID = ${API_ID}
API_HASH = "${API_HASH}"
BOT_TOKEN = "${BOT_TOKEN}"
OWNER_ID = ${OWNER_ID}
STRING_SESSION = ""
AI_API_KEY = "${AI_KEY}"
EOF

  chmod 600 "${DIR}/config.py"
  ok "config.py created (permissions: 600)"
  info "✨ Everything formatted automatically — no manual editing needed!"
fi

# ── 4/5 systemd service ──
step "4/5  Creating systemd service (24/7)..."
cat > /etc/systemd/system/userbot.service <<EOF
[Unit]
Description=3OUTHBOY UserBot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${DIR}
ExecStart=${DIR}/venv/bin/python bot.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
ok "Service created"

# ── 5/5 first login ──
step "5/5  First login (Telegram)"
echo -e "${Y}  The bot will now start and ask for your phone number${R}"
echo -e "${Y}  and a login code (the code arrives INSIDE your Telegram${R}"
echo -e "${Y}  app — in the chat named 'Telegram', not by SMS).${R}"
echo -e "${Y}  After it says the bot is online, press Ctrl+C to finish.${R}"
echo
read -p "  Start login now? (Y/n): " DOLOGIN
if [[ "$DOLOGIN" != "n" ]]; then
  cd "${DIR}"
  "${DIR}/venv/bin/python" bot.py || true
fi

# ── enable & start service ──
step "Starting service..."
systemctl enable --now userbot
sleep 3
systemctl status userbot --no-pager -l | head -n 12

echo
echo -e "${C}${LINE}${R}"
echo -e "${G}${B}  ✅ Installation complete!${R}"
echo -e "${C}${LINE}${R}"
cat <<EOF

  🖥  Server Manager (recommended):
       python3 manager.py
       A beautiful control panel — status, logs, backup,
       update, uninstall & more, with a simple number menu!

  🛠  Classic management commands:
       journalctl -u userbot -f        live logs
       systemctl restart userbot       restart (after code changes)
       systemctl stop userbot          stop
       systemctl start userbot         start

  📚  Usage:
       Bot chat:   /panel
       Any chat:   .panel

EOF

read -p "  🖥  Open the Server Manager panel now? (y/N): " OPENMGR
if [[ "$OPENMGR" == "y" ]]; then
  cd "${DIR}"
  python3 manager.py
else
  echo -e "${C}  💡 Tip: run  python3 manager.py  anytime.${R}"
fi
